### PR TITLE
Publish pre-release automatically

### PR DESCRIPTION
**Pull request by kamaradclimber**

### CODE REVIEW

**Comment by thommay** [comment]
@kamaradclimber chefstyle is unhappy with you, but other than that 👍

**Comment by kamaradclimber** [comment]
I don't really understand appveyor. For every PR I've done on this repo, it never seems to be happy :cry:

**Comment by thommay** [comment]
i think that's actually a straight up chefstyle bug. We need to fix `Layout/EndOfLine` to `lf` rather than native.

**Comment by thommay** [comment]
https://github.com/chef/chefstyle/pull/52

**Pull request merged**
