### PR TITLE
Support errors on clients while refreshing vaults

### LINKED ISSUE #225: Knife vault refresh fails: `Error: Missing read permission`
Hello,

I am facing an issue with `knife vault refresh` and have this blurry message.

```
Starting run 1474473841 (Wed Sep 21 16:04:01 UTC 2016)
--> Knife using Chef-vault Gem:
2.9.0
...

knife vault refresh shared_secrets VAULT_ITEM

Refreshing shared_secrets/VAULT_ITEM
ERROR: You authenticated successfully to https://127.0.0.1/organizations/ORG_NAME as USERX but you are not authorized for this action
Response:  missing read permission
```

We are using:
- chef-server `12.4.1`
- A cron based job that does a `knife vault refresh` periodically to update the clients list for each vault items according to the `search_query`

Everything was working well and suddenly, with no obvious reasons and changes, we have this error.

I have already read the issue #171 but it does not seem to be related.

More info:
### Workstation

```
$ ruby --version
ruby 2.1.8p440 (2015-12-16 revision 53160)
```

```
chef --version
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
### My Chef repo

```
git:(master)   $ grep chef Gemfile.lock

    chef (12.13.37)
    chef-config (12.13.37)
    chef-dk (0.17.17)
    chef-provisioning (1.9.1)
    chef-vault (2.9.0)
    chef-zero (4.9.0)
    cheffish (3.0.1)
    chefspec (5.1.1)
    librarian-chef (0.0.4)
```
### Chef-server

```
[chef02 ~] $ yum list installed | grep -i chef
chef.x86_64                    12.8.1-1.el6              installed
chef-server-core.x86_64        12.4.1-1.el6              installed
```

### PR DESCRIPTION
**Pull request by xakraz**
This PR adds support for errors from `Chef::ApiClient` and fix #225

Previously, any low level errors (`Net::HttpServerExceptions`) thrown by a remote `chef-server` during `knife` calls made the `knife vault refresh` fail with unclear messages.

Now, it gives a warning message when something went wrong for a specific client and skips it (Same behaviour as when a node `has no private key`).

### CODE REVIEW

**Comment by xakraz** [comment]
This MR is a bugfix fo v2.9.0 -> 2.9.1

## How to reproduce

1. On a Chef-server installed via Omnibus package (Chef-server official cookbook):

```
$ sudo yum list installed | grep -i chef
chef.x86_64                    12.8.1-1.el6              installed
chef-server-core.x86_64        12.4.1-1.el6              installed
```

2. Edit the embedded Nginx conf: `/var/opt/opscode/nginx/etc/chef_https_lb.conf`

Add these lines before the 1st `location` statement:

```
location "/organizations/ORG_NAME/clients/FAULTY_CLIENT_NAME" {
      return 403 "test - Chef-server - Missing Read Permission";
    }
```

3. Run `knife vault refresh` for the secret where the `search_query` match the faulty client

```
knife vault refresh VAULT_NAME VAULT_ITEM

ERROR: You authenticated successfully to https://127.0.0.1/organizations/ORG_NAME as USERx but you are not authorized for this action
Response:  test - Chef-server - Missing Read Permission
```

## Results

* The vault is not updated
* The command returns an error exit code
* You don't really know if the issue is from Chef-server-12 ACL model or anything ...

**Comment by xakraz** [comment]
@thommay : Any feedback about this PR ?

Thanks and sorry for the direct ping ...

**Comment by thommay** [comment]
Hi, please could you rebase on to master? That should remove the need for the rubocop changes and make the whole thing much easier to review. (I don't intend to do another 2.x release unless I really need to).

**Comment by thommay** [comment]
(sorry for the slow response, been away for the last couple of weeks)

**Comment by xakraz** [comment]
Hi @thommay,

Sorry for the late response too (Mail filtering issue ^^).

I tried to rebase my changes on master as requested, however it is more difficult for me than expected. A lot of changes have been introduced in your 3.0-pre work (In fact, most of the changes have been introduced by #209).

By the way, this late PR mostly fixes my issue with a better error message, so I don't really need my patch if there is a release including this one.

I understand you do not wish to release a new 2.x release but this change, from the 22nd of April, is really important since the introduction of Chef-server 12.x. and especially chef-server >= 12.5.x (2016-03)

**Comment by thommay** [comment]
Yes, that change is most of the point of doing 3.0. I'm hoping to have a release candidate out today or tomorrow. In the meantime I'll close this PR since you agree that it's mostly superseded.

**Pull request closed without merging**
