### PR TITLE
Don't create blank entries in *_keys entries

### PR DESCRIPTION
**Pull request by hfinucane**
#182

### CODE REVIEW

**Comment by oifland** [comment]
Is there a way to reproduce the issue you had with a unit test? I'm a little fuzzy on what's being fixed.

**Comment by muhh** [comment]
This brought chef-vault to a usable state. 
Before using search_query does not have any effect at all.

Looking forward to a merge and release!

**Comment by martinisoft** [comment]
Just had to manually patch my chef-vault to get past this bug too. Any chance of a merge and release before the end of the year?

**Comment by martinisoft** [comment]
Actually #184 seems like a more backward compatible solution if we have an API regression happening.

**Comment by thommay** [comment]
I merged #184 in preference, so closing. Thanks for the contribution!

**Pull request closed without merging**
