### PR TITLE
expose secret key for initial host provisioning

### PR DESCRIPTION
**Pull request by pburkholder**
This addresses the 'chicken-and-egg' problem that @jtimberman alludes to in http://jtimberman.housepub.org/blog/2013/09/10/managing-secrets-with-chef-vault/.  I'm only starting to test this in EC2, but I thought I should submit a PR for feedback sooner rather than later.
## Using Shared Secrets

When instantiating new nodes, you may need to access the vault
with the symmetric key in the same way would with a standard
encrypted data bag, as in the following workflow:
- Save the current vault secret to a file with 'knife encrypt expose key'
- Encode the secret so it's available to node at launch, e.g. userdata.txt for EC2.
- Launch node for initial provisioning, then wipe the secrets file from disk
- Rekey the vault with 'knife encrypt rotate keys'
- Update the vault ('knife encrypt update') with an updated node search so the new node has keys encrypted with its private key.
#### Example Code

Recipe:

``` ruby
passwords = ChefVault::Item.load("password", "root", "/etc/chef/vault_secret")
```

And for key management:

``` shell
knife encrypt expose key password root --mode client --secret-file vault_secret
# provision node with 'vault_secret'
knife encrypt rotate keys password root --mode client
knife encrypt update password root --search 'role:base' --mode client
```

### CODE REVIEW

**Comment by jtimberman** [comment]
I believe the "chicken and egg" issue is solved by the new options added to Chef in a recent version (12.2 I think?)

```
--bootstrap-vault-file VAULT_FILE
Use to specify the path to a JSON file that contains a list of vaults and items to be updated.
--bootstrap-vault-item VAULT_ITEM
Use to specify a single vault and item to update as vault:item.
--bootstrap-vault-json VAULT_JSON
Use to specify a JSON string that contains a list of vaults and items to be updated.
```

https://docs.chef.io/knife_bootstrap.html

**Comment by jf647** [comment]
Indeed the vault support in bootstrap solves the problem for some use cases, specifically ones in which the provisioning step can be launched from your knife-equipped workstation.  Terraform and Chef Provisioning work this way.

It doesn't work so well when the initial provisioning is kicked off from your stack engine, as with CloudFormation.

This cookbook:

https://supermarket.chef.io/cookbooks/chef_vault_try_notify

is the first part of our attempt to solve the latter use case - it calls a ruby block if the vault secrets are not available and comes with a handler to send an SNS notification.  We're working on the other half - the thing that receives the notifications and refreshes the vaults, but more to come on that front in a couple of weeks I hope.

**Comment by pburkholder** [comment]
https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8298918-chef-client-equivalent-of-knife-bootstrap-bootst -- feature request for provisioning

**Comment by kamaradclimber** [comment]
I think we can close this PR since there is no activity anymore. Feel free to open an issue to restart the discussion if needed.

**Pull request closed without merging**
