### PR TITLE
Optimize split_vault_keys method for large bag

### PR DESCRIPTION
**Pull request by Annih**
## Description

With 10k secrets the regexp union is quite big and applying it to the 20k keys takes around 2 minutes...
Also the Regexp was too greedy and could match normal items as sparse one.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by Annih** [comment]
Hum it seems I duplicated #360 fixes, should I remove that from my PR and rebase on top of it?

**Comment by tas50** [comment]
@Annih I can just cherry pick out the main fix here unless you want to rebase it without that change.

**Review by lamont-granquist — APPROVED** [review]

**Comment by tas50** [comment]
Merged in #364

**Comment by Annih** [comment]
Thanks @tas50 !

**Pull request closed without merging**
