### PR TITLE
Minimize the number of searches

### PR DESCRIPTION
**Pull request by thommay**
This shows about a 40% improvement in run times when using `clean-unkown-clients` with refresh.

### CODE REVIEW

**Comment by thommay** [comment]
@rveznaver @lamont-granquist @kamaradclimber

**Comment by kamaradclimber** [comment]
Lgtm i' ll try to test on monday
Thanks for the notification

**Comment by rveznaver** [comment]
Looks fine, but not sure if adding another state (```@current_query```) and increasing the mutability of an ```Item``` object is the way to go in the long term.

**Comment by lamont-granquist** [comment]
👍

**Pull request merged**
